# This file was generated by GoReleaser. DO NOT EDIT.
cask "fireflies" do
  version "1.0.2"

  on_macos do
    on_intel do
      url "https://github.com/fvdm-otinga/fireflies-cli/releases/download/v#{version}/fireflies_#{version}_darwin_amd64.tar.gz"
      sha256 "fec1b06c4870ba72c314a64c2b3315244d9c9183a6bae2ab397f793c577c2dd0"
    end
    on_arm do
      url "https://github.com/fvdm-otinga/fireflies-cli/releases/download/v#{version}/fireflies_#{version}_darwin_arm64.tar.gz"
      sha256 "39a92ad60d0f703ce51b6fe2888f749acde21e5b4af47ca1a9ed18ee14ac29ee"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fvdm-otinga/fireflies-cli/releases/download/v#{version}/fireflies_#{version}_linux_amd64.tar.gz"
      sha256 "7e7bbf2bc0a918f4fee1ebc4575897017f9a6faf17fcb86f9e27b6728bc03184"
    end
    on_arm do
      url "https://github.com/fvdm-otinga/fireflies-cli/releases/download/v#{version}/fireflies_#{version}_linux_arm64.tar.gz"
      sha256 "5362fb6ec6bfb9fbd5f0ee45fec6b458868bd7b9596761889411ee519128476a"
    end
  end

  name "fireflies"
  desc "Token-efficient CLI for the Fireflies.ai GraphQL API"
  homepage "https://github.com/fvdm-otinga/fireflies-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fireflies"

  # No zap stanza required

end
