# This file was generated by GoReleaser. DO NOT EDIT.
cask "fireflies" do
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/fvdm-otinga/fireflies-cli/releases/download/v#{version}/fireflies_#{version}_darwin_amd64.tar.gz"
      sha256 "6e155c2ed3be23c19e39ea4b71191db4acc4124adb17209c9fcabe47561dc9ad"
    end
    on_arm do
      url "https://github.com/fvdm-otinga/fireflies-cli/releases/download/v#{version}/fireflies_#{version}_darwin_arm64.tar.gz"
      sha256 "c79ae47e4fb72b819e89d25840e1de84275042f477e773faf7bbd0ee58a8b294"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fvdm-otinga/fireflies-cli/releases/download/v#{version}/fireflies_#{version}_linux_amd64.tar.gz"
      sha256 "524c5fc7ee04c64933ca771ea96f1382e644764afb69f8503dac426090a5f716"
    end
    on_arm do
      url "https://github.com/fvdm-otinga/fireflies-cli/releases/download/v#{version}/fireflies_#{version}_linux_arm64.tar.gz"
      sha256 "4adf70b48d235e1bd4b6826e633486dc9ccf7ae734167a962cd808a3cb002040"
    end
  end

  name "fireflies"
  desc "Token-efficient CLI for the Fireflies.ai GraphQL API"
  homepage "https://github.com/fvdm-otinga/fireflies-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fireflies"

  # No zap stanza required

end
