# This file was generated by GoReleaser. DO NOT EDIT.
cask "fireflies" do
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/fvdm-otinga/fireflies-cli/releases/download/v#{version}/fireflies_#{version}_darwin_amd64.tar.gz"
      sha256 "07735ac1c3bb6c6d8f48a0542713755bfcab753725c5088b78992bb870825cb6"
    end
    on_arm do
      url "https://github.com/fvdm-otinga/fireflies-cli/releases/download/v#{version}/fireflies_#{version}_darwin_arm64.tar.gz"
      sha256 "c916e89533cc8897960461f72ec739c0f92bc776b2a6dd36d8be1de52633f155"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fvdm-otinga/fireflies-cli/releases/download/v#{version}/fireflies_#{version}_linux_amd64.tar.gz"
      sha256 "2219e37cc10055c4b67fc9109ddf7df9260673445f5c02e6d9e9ef6aca603194"
    end
    on_arm do
      url "https://github.com/fvdm-otinga/fireflies-cli/releases/download/v#{version}/fireflies_#{version}_linux_arm64.tar.gz"
      sha256 "c315018c981e9dd6225ebbda1fb1405fe1d0a425e2d449589fd6e9fd623e8cf1"
    end
  end

  name "fireflies"
  desc "Token-efficient CLI for the Fireflies.ai GraphQL API"
  homepage "https://github.com/fvdm-otinga/fireflies-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fireflies"

  # No zap stanza required

end
